//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSp { get; set; }
        public string TenSp { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> SoLanMua { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public string DaXoa { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string HinhAnh4 { get; set; }
        public Nullable<int> Moi { get; set; }
        public string CauHinh { get; set; }
        public string UrlName { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
